name: CI

on:
  - push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Create file 
        env: 
          K8S_SECRET: ${{ secrets.K8S_SECRET }}
        run: echo "$K8S_SECRET" >> $PWD/secret.yaml 
      - name : read secret
        run : cat secret.yaml
      
      - name: Upload math result for job 1
        uses: actions/upload-artifact@v2
        with:
          name: homework
          path: .
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
          
      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f secret.yaml -n githubaction
