name: CI

on:
  - push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Download math result for job 2
        uses: actions/download-artifact@v2
        with:
          name: homework
      - name: Create file 
        env: 
          K8S_SECRET: ${{ secrets.K8S_SECRET }}
        run: echo "$K8S_SECRET" >> secret.yaml 
      - name : read secret
        run : cat secret.yaml

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f secret.yaml -n githubaction
