name: CI

on:
  - push

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Create file 
        env: 
          K8S_SECRET_FILE: ${{ secrets.K8S_SECRET }}
        run: echo "$K8S_SECRET_FILE" >> secret.yaml 
      - name : read secret
        run : cat secret.yaml

      - name: Trigger deploy
        uses: Consensys/kubernetes-action@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: apply -f deployment.yaml -n githubaction
